# Generated by Django 3.0.9 on 2020-08-27 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodsinfo',
            old_name='gkucun',
            new_name='gstock',
        ),
    ]
