# Generated by Django 3.0.9 on 2020-08-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='user',
            new_name='ouser',
        ),
    ]
