# Generated by Django 3.0.9 on 2020-08-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_order', '0002_auto_20200827_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='oIsPay',
            new_name='oIspay',
        ),
    ]
